## PANDAS


In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('Used_Bikes.csv')

In [5]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [7]:
df.head()  # top 5 rows

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [8]:
df.tail()  # bottom 5 rows

bike_name    price    city  kms_driven        owner  \
32643     Hero Passion Pro 100cc  39000.0   Delhi     22000.0  First Owner   
32644       TVS Apache RTR 180cc  30000.0  Karnal      6639.0  First Owner   
32645   Bajaj Avenger Street 220  60000.0   Delhi     20373.0  First Owner   
32646  Hero Super Splendor 125cc  15600.0  Jaipur     84186.0  First Owner   
32647         Bajaj Pulsar 150cc  22000.0    Pune     60857.0  First Owner   

        age  power  brand  
32643   4.0  100.0   Hero  
32644   9.0  180.0    TVS  
32645   6.0  220.0  Bajaj  
32646  16.0  125.0   Hero  
32647  13.0  150.0  Bajaj

In [9]:
df.info()  # info about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [10]:
df.describe()   #summary of data

price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [11]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(25324)

In [13]:
32648-25324


7324

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['bike_name'].unique()

array(['TVS Star City Plus Dual Tone 110cc',
       'Royal Enfield Classic 350cc', 'Triumph Daytona 675R',
       'TVS Apache RTR 180cc', 'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
       'Yamaha FZs 150cc', 'Honda CB Hornet 160R  ABS DLX',
       'Hero Splendor Plus Self Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc',
       'Royal Enfield Classic Desert Storm 500cc',
       'Yamaha YZF-R15 2.0 150cc', 'Yamaha FZ25 250cc',
       'Bajaj Pulsar NS200', 'Bajaj Discover 100M', 'Bajaj Discover 125M',
       'Bajaj Pulsar NS200 ABS', 'Bajaj Pulsar RS200 ABS',
       'Suzuki Gixxer SF 150cc', 'Benelli 302R 300CC',
       'Hero Splendor iSmart Plus IBS 110cc',
       'Royal Enfield Classic Chrome 500cc', 'Yamaha FZ V 2.0 150cc',
       'Hero Super Splendor 125cc', 'Honda CBF Stunner 125cc',
       'Bajaj Pulsar 150cc', 'Honda X-Blade 160CC ABS',
       'Bajaj Avenger 220cc', 'KTM RC 390cc', 'Honda CB Unicorn 150cc',
       'KTM Duke 200cc', 'Honda CBR 150R 150cc',
       'Royal Enfiel

In [17]:
df['brand']

0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...       
9362               Hero
9369              Bajaj
9370    Harley-Davidson
9371              Bajaj
9372              Bajaj
Name: brand, Length: 7324, dtype: object

In [18]:
df['owner']

0       First Owner
1       First Owner
2       First Owner
3       First Owner
4       First Owner
           ...     
9362    First Owner
9369    First Owner
9370    First Owner
9371    First Owner
9372    First Owner
Name: owner, Length: 7324, dtype: object

In [19]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [20]:
df['brand'].unique

<bound method Series.unique of 0                   TVS
1         Royal Enfield
2               Triumph
3                   TVS
4                Yamaha
             ...       
9362               Hero
9369              Bajaj
9370    Harley-Davidson
9371              Bajaj
9372              Bajaj
Name: brand, Length: 7324, dtype: object>

In [21]:
print("unique values:",df['bike_name'].unique())
print(df['bike_name'].nunique())

unique values: ['TVS Star City Plus Dual Tone 110cc' 'Royal Enfield Classic 350cc'
 'Triumph Daytona 675R' 'TVS Apache RTR 180cc'
 'Yamaha FZ S V 2.0 150cc-Ltd. Edition' 'Yamaha FZs 150cc'
 'Honda CB Hornet 160R  ABS DLX' 'Hero Splendor Plus Self Alloy 100cc'
 'Royal Enfield Thunderbird X 350cc'
 'Royal Enfield Classic Desert Storm 500cc' 'Yamaha YZF-R15 2.0 150cc'
 'Yamaha FZ25 250cc' 'Bajaj Pulsar NS200' 'Bajaj Discover 100M'
 'Bajaj Discover 125M' 'Bajaj Pulsar NS200 ABS' 'Bajaj Pulsar RS200 ABS'
 'Suzuki Gixxer SF 150cc' 'Benelli 302R 300CC'
 'Hero Splendor iSmart Plus IBS 110cc'
 'Royal Enfield Classic Chrome 500cc' 'Yamaha FZ V 2.0 150cc'
 'Hero Super Splendor 125cc' 'Honda CBF Stunner 125cc'
 'Bajaj Pulsar 150cc' 'Honda X-Blade 160CC ABS' 'Bajaj Avenger 220cc'
 'KTM RC 390cc' 'Honda CB Unicorn 150cc' 'KTM Duke 200cc'
 'Honda CBR 150R 150cc' 'Royal Enfield Thunderbird X 500cc'
 'KTM RC 200cc ABS' 'Royal Enfield Thunderbird 350cc'
 'Royal Enfield Bullet Electra 350cc' 'Bajaj Aveng

In [22]:
print("unique values of brand :-",df['brand'].unique())
print("total unique values of brand :-",df['brand'].nunique())

unique values of brand :- ['TVS' 'Royal Enfield' 'Triumph' 'Yamaha' 'Honda' 'Hero' 'Bajaj' 'Suzuki'
 'Benelli' 'KTM' 'Mahindra' 'Kawasaki' 'Ducati' 'Hyosung'
 'Harley-Davidson' 'Jawa' 'BMW' 'Indian' 'Rajdoot' 'LML' 'Yezdi' 'MV'
 'Ideal']
total unique values of brand :- 23


In [23]:
df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [24]:
df=df.drop(['city','bike_name'],axis=1)

In [25]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [26]:
cat_cols=df.select_dtypes(include='object')

In [27]:
cat_cols

owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [28]:
num_cols=df.select_dtypes(exclude='object')

In [29]:
num_cols

price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [30]:
cat_cols['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [31]:
ower_dict={'First Owner':0, 'Second Owner':1, 'Third Owner':2,
       'Fourth Owner Or More':3}

In [32]:
ower_dict

{'First Owner': 0,
 'Second Owner': 1,
 'Third Owner': 2,
 'Fourth Owner Or More': 3}

In [33]:
cat_cols['owner']=cat_cols['owner'].map(ower_dict)

In [34]:
cat_cols

owner            brand
0         0              TVS
1         0    Royal Enfield
2         0          Triumph
3         0              TVS
4         0           Yamaha
...     ...              ...
9362      0             Hero
9369      0            Bajaj
9370      0  Harley-Davidson
9371      0            Bajaj
9372      0            Bajaj

[7324 rows x 2 columns]

In [35]:
cat_cols['owner'].unique()

array([0, 1, 2, 3])

In [36]:
cat_cols['brand'].unique()  

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [37]:
brand_dict ={'TVS':0, 'Royal Enfield':1, 'Triumph':2, 'Yamaha':3, 'Honda':4, 'Hero':5,
       'Bajaj':6, 'Suzuki':7, 'Benelli':8, 'KTM':9, 'Mahindra':10, 'Kawasaki':11,
       'Ducati':12, 'Hyosung':13, 'Harley-Davidson':14, 'Jawa':15, 'BMW':16, 'Indian':17,
       'Rajdoot':18, 'LML':19, 'Yezdi':20, 'MV':21, 'Ideal':22}

In [38]:
cat_cols['brand']=cat_cols['brand'].map(brand_dict)

In [39]:
cat_cols

owner  brand
0         0      0
1         0      1
2         0      2
3         0      0
4         0      3
...     ...    ...
9362      0      5
9369      0      6
9370      0     14
9371      0      6
9372      0      6

[7324 rows x 2 columns]

In [40]:
complete_df =pd.concat([cat_cols,num_cols],axis=1)

In [41]:
complete_df

owner  brand     price  kms_driven  age  power
0         0      0   35000.0     17654.0  3.0  110.0
1         0      1  119900.0     11000.0  4.0  350.0
2         0      2  600000.0       110.0  8.0  675.0
3         0      0   65000.0     16329.0  4.0  180.0
4         0      3   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
9362      0      5   25000.0     48587.0  8.0  150.0
9369      0      6   35000.0     60000.0  9.0  220.0
9370      0     14  450000.0      3430.0  4.0  750.0
9371      0      6  139000.0     21300.0  4.0  400.0
9372      0      6   80000.0      7127.0  5.0  220.0

[7324 rows x 6 columns]

In [42]:
x=complete_df.drop('price',axis=1)  #cols=1---axis=1
y=complete_df[['price']]



In [43]:
x  # independent variable

owner  brand  kms_driven  age  power
0         0      0     17654.0  3.0  110.0
1         0      1     11000.0  4.0  350.0
2         0      2       110.0  8.0  675.0
3         0      0     16329.0  4.0  180.0
4         0      3     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
9362      0      5     48587.0  8.0  150.0
9369      0      6     60000.0  9.0  220.0
9370      0     14      3430.0  4.0  750.0
9371      0      6     21300.0  4.0  400.0
9372      0      6      7127.0  5.0  220.0

[7324 rows x 5 columns]

In [44]:
y   # dependent variable

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [45]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [46]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0)

In [47]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

## LinearRegression

In [48]:
from sklearn.linear_model import LinearRegression

In [49]:
lr=LinearRegression()

In [50]:
lr.fit(x_train,y_train)

LinearRegression()

In [51]:
lr.score(x_test,y_test)

0.7530846908957266

In [52]:
lr.score(x_train,y_train)

0.7104324344011279

## SVR

In [53]:
from sklearn.svm import SVR

In [54]:
Ssvr_obj=SVR()

In [55]:
Ssvr_obj.fit(x_train,y_train)

c:\Users\Jyoti Kumari\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [56]:
Ssvr_obj.score(x_train,y_train)

-0.05828152912902218

In [57]:
Ssvr_obj.score(x_test,y_test)

-0.07184108083361518

## knn


In [58]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [59]:
knr=KNeighborsRegressor()

In [60]:
knr.fit(x_train,y_train)



KNeighborsRegressor()

In [61]:
print("testing score:- ",knr.score(x_test,y_test))

testing score:-  0.6239911003208788


In [62]:
print("training score:- ",knr.score(x_train,y_train))

training score:-  0.7854018315459385


In [63]:
knr.predict(x_test)

array([[ 40838.],
       [112740.],
       [ 54000.],
       ...,
       [ 37000.],
       [ 33960.],
       [ 61600.]], shape=(1465, 1))

In [64]:
from sklearn.tree  import DecisionTreeRegressor,DecisionTreeClassifier

In [65]:
dtr=DecisionTreeRegressor()

In [66]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [67]:
print("testing score:- ",dtr.score(x_test,y_test))

testing score:-  0.8228585194092025


In [68]:
print("training score:- ",dtr.score(x_train,y_train))

training score:-  0.9980046623640842


In [69]:
dtr.predict(x_test)

array([ 33000., 140000.,  30000., ...,  31500.,  18000., 110000.],
      shape=(1465,))

In [70]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [71]:
rfr=RandomForestRegressor()

In [72]:
rfr.fit(x_train,y_train)

c:\Users\Jyoti Kumari\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [73]:
print("testing score:- ",rfr.score(x_test,y_test))

testing score:-  0.9100460920852729


In [74]:
print("training score:- ",rfr.score(x_train,y_train))

training score:-  0.9831152569720419


In [75]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print(gnb.score(x_test,y_test))
print(gnb.score(x_train,y_train))

0.021843003412969283


c:\Users\Jyoti Kumari\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.16999487967229904


In [76]:
from sklearn.datasets import load_iris
data=load_iris()
x=data.data
y=data.target

In [77]:
x


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [78]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [79]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print("testing score:-",gnb.score(x_test,y_test))
print("training score:",gnb.score(x_train,y_train))


testing score:- 0.9666666666666667
training score: 0.9583333333333334


In [80]:
from sklearn.ensemble import RandomForestRegressor

rf =RandomForestRegressor()

rf.fit(x_train,y_train)

print("testing score :-",rf.score(x_test,y_test))

print("training score :-",rf.score(x_train,y_train))

testing score :- 0.9784614093959731
training score :- 0.9909987494789496


In [81]:
import joblib
joblib.dump(rf,"bike_price.joblib")

['bike_price.joblib']

In [82]:
model=joblib.load("bike_price.joblib")

In [83]:
model.predict([[5.1,3.5,1.4,0.2]])

array([0.])

In [84]:
pred=model.predict(x_test)

In [85]:
pred

array([2.  , 2.  , 2.  , 1.01, 1.  , 1.  , 0.  , 0.  , 1.  , 1.38, 1.  ,
       2.  , 0.  , 0.  , 2.  , 0.  , 1.19, 0.  , 0.  , 0.  , 2.  , 1.  ,
       0.  , 1.97, 1.08, 2.  , 1.  , 0.  , 1.  , 0.  ])

In [86]:
prediction_history={"prediction_price":pred,"actual_price":y_test}

In [87]:
pd.DataFrame(prediction_history)

prediction_price  actual_price
0               2.00             2
1               2.00             2
2               2.00             2
3               1.01             1
4               1.00             1
5               1.00             1
6               0.00             0
7               0.00             0
8               1.00             1
9               1.38             2
10              1.00             1
11              2.00             2
12              0.00             0
13              0.00             0
14              2.00             2
15              0.00             0
16              1.19             1
17              0.00             0
18              0.00             0
19              0.00             0
20              2.00             2
21              1.00             1
22              0.00             0
23              1.97             2
24              1.08             1
25              2.00             2
26              1.00             1
27              0.00             0
28              1.00             1
29              0.00             0