In [9]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np
import pandas as pd

In [11]:
df=pd.read_csv("https://raw.githubusercontent.com/upflairs-pvt-ltd/3rd_july_datascience/master/farmer_guider/farmer.csv")

In [12]:
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [13]:
df.head()  # top 5 rows

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [14]:
df.tail()  # bottom 5 rows

N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [15]:
df.info()  # info about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [16]:
df.describe()   #summary of data

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [17]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [80]:
label=df[df['label']=="rice"]

In [81]:
temp=label[label['temperature']<=80]

In [257]:
ph1=temp[temp['ph']<=60]

In [258]:
ph1

N   P   K  temperature   humidity        ph    rainfall label
0   90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1   85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2   60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3   74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4   78  42  42    20.130175  81.604873  7.628473  262.717340  rice
..  ..  ..  ..          ...        ...       ...         ...   ...
95  88  46  42    22.683191  83.463583  6.604993  194.265172  rice
96  93  47  37    21.533463  82.140041  6.500343  295.924880  rice
97  60  55  45    21.408658  83.329319  5.935745  287.576694  rice
98  78  35  44    26.543481  84.673536  7.072656  183.622266  rice
99  65  37  40    23.359054  83.595123  5.333323  188.413665  rice

[100 rows x 8 columns]

In [259]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [260]:
print("unique values:",df['label'].unique())
print(df['label'].nunique())

unique values: ['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']
22


In [261]:
df['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [262]:
cat_cols=df.select_dtypes(include='object')

In [263]:
cat_cols

label
0       rice
1       rice
2       rice
3       rice
4       rice
...      ...
2195  coffee
2196  coffee
2197  coffee
2198  coffee
2199  coffee

[2200 rows x 1 columns]

In [264]:
num_cols=df.select_dtypes(exclude='object')

In [265]:
num_cols

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [266]:
cat_cols['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [267]:
label_dict={'rice':0, 'maize':1, 'chickpea':2, 'kidneybeans':3, 'pigeonpeas':4,
       'mothbeans':5, 'mungbean':6, 'blackgram':7, 'lentil':8, 'pomegranate':9,
       'banana':10, 'mango':11, 'grapes':12, 'watermelon':13, 'muskmelon':14, 'apple':15,
       'orange':16, 'papaya':17, 'coconut':18, 'cotton':19, 'jute':20, 'coffee':21}

In [268]:
cat_cols['label']=cat_cols['label'].map(label_dict)

In [269]:
complete_df =pd.concat([cat_cols,num_cols],axis=1)

In [270]:
complete_df

label    N   P   K  temperature   humidity        ph    rainfall
0         0   90  42  43    20.879744  82.002744  6.502985  202.935536
1         0   85  58  41    21.770462  80.319644  7.038096  226.655537
2         0   60  55  44    23.004459  82.320763  7.840207  263.964248
3         0   74  35  40    26.491096  80.158363  6.980401  242.864034
4         0   78  42  42    20.130175  81.604873  7.628473  262.717340
...     ...  ...  ..  ..          ...        ...       ...         ...
2195     21  107  34  32    26.774637  66.413269  6.780064  177.774507
2196     21   99  15  27    27.417112  56.636362  6.086922  127.924610
2197     21  118  33  30    24.131797  67.225123  6.362608  173.322839
2198     21  117  32  34    26.272418  52.127394  6.758793  127.175293
2199     21  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 8 columns]

In [271]:
x=complete_df.drop('label',axis=1)  #cols=1---axis=1
y=complete_df[['label']]



In [272]:
x

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [273]:
y

label
0         0
1         0
2         0
3         0
4         0
...     ...
2195     21
2196     21
2197     21
2198     21
2199     21

[2200 rows x 1 columns]

In [274]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [275]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0)

In [276]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1760, 7), (440, 7), (1760, 1), (440, 1))

In [277]:
from sklearn.linear_model import LinearRegression

In [278]:
lr=LinearRegression()

In [279]:
lr.fit(x_train,y_train)

LinearRegression()

In [280]:
lr.score(x_test,y_test)

0.36410422034318835

In [281]:
lr.score(x_train,y_train)

0.3843736913831781

In [282]:
from sklearn.svm import SVR

In [283]:
Ssvr_obj=SVR()

In [284]:
Ssvr_obj.fit(x_train,y_train)

c:\Users\Jyoti Kumari\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [285]:
Ssvr_obj.score(x_train,y_train)

0.6294435195790303

In [286]:
Ssvr_obj.score(x_test,y_test)

0.6063610901652179

In [287]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [288]:
knr=KNeighborsRegressor()

In [289]:
knr.fit(x_train,y_train)



KNeighborsRegressor()

In [290]:
print("testing score:- ",knr.score(x_test,y_test))

testing score:-  0.8879060564137722


In [291]:
print("training score:- ",knr.score(x_train,y_train))

training score:-  0.9419741341827814


In [292]:

knr.predict(x_test)

array([[13. ],
       [13. ],
       [12. ],
       [ 2. ],
       [ 7. ],
       [16. ],
       [ 5. ],
       [ 3. ],
       [14. ],
       [10. ],
       [ 5.6],
       [21. ],
       [ 8. ],
       [ 6. ],
       [11. ],
       [15. ],
       [21. ],
       [ 8. ],
       [21. ],
       [11. ],
       [18. ],
       [ 7. ],
       [ 3. ],
       [12. ],
       [19. ],
       [20.8],
       [ 8. ],
       [16. ],
       [ 5. ],
       [ 3. ],
       [ 9. ],
       [ 0. ],
       [ 1. ],
       [14. ],
       [18. ],
       [19. ],
       [11. ],
       [11. ],
       [13. ],
       [ 5.8],
       [ 1. ],
       [ 7. ],
       [ 4. ],
       [13. ],
       [ 4. ],
       [ 6. ],
       [ 3. ],
       [ 3. ],
       [19. ],
       [ 6. ],
       [ 5. ],
       [ 7. ],
       [15. ],
       [14. ],
       [ 4. ],
       [10. ],
       [17. ],
       [11. ],
       [ 8. ],
       [19. ],
       [16. ],
       [ 6. ],
       [13. ],
       [ 0. ],
       [14. ],
       [15. ],
       [12

In [293]:
from sklearn.tree  import DecisionTreeRegressor,DecisionTreeClassifier

In [294]:
dtr=DecisionTreeRegressor()

In [295]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [296]:
print("testing score:- ",dtr.score(x_test,y_test))



testing score:-  0.8902113361221382


In [297]:
print("training score:- ",dtr.score(x_train,y_train))

training score:-  1.0


In [298]:
dtr.predict(x_test)

array([13., 13., 12.,  2.,  7.,  0.,  5.,  3., 14., 10.,  5., 21.,  8.,
        6., 11., 15., 21.,  8., 21., 11., 18.,  7.,  3., 20., 19., 21.,
        8., 16.,  5.,  1.,  9.,  0.,  1., 14., 18., 19., 11., 11., 13.,
        7.,  1.,  7.,  4., 13.,  4.,  6.,  3.,  3., 19.,  6.,  5.,  7.,
       15., 14.,  4., 10., 17., 11.,  8., 19., 16.,  6., 13.,  0., 14.,
       15., 12., 21., 15., 16., 18.,  9.,  3., 19., 12.,  5.,  2.,  1.,
        0., 11.,  0.,  7., 13., 13., 14., 19.,  1.,  8.,  5., 17.,  7.,
       20.,  6., 12.,  6.,  1., 21., 20.,  8.,  2., 16., 20.,  6., 10.,
       10.,  0., 13., 21.,  4., 14., 14., 11., 21., 12., 16.,  9.,  6.,
        8.,  1., 20.,  9.,  8., 16.,  2.,  2.,  7.,  9., 16.,  2., 17.,
        5.,  5., 14.,  6.,  1.,  6., 18.,  9., 16.,  7.,  7., 12., 15.,
       21.,  2., 15., 20., 11., 13., 17., 16., 18.,  5., 10.,  9.,  2.,
       13.,  7., 15., 20.,  8.,  4., 20.,  3.,  3., 14.,  0., 14., 10.,
       16.,  4., 15.,  5., 18., 19.,  6.,  3.,  9., 17., 16.,  0

In [299]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [300]:
rfr=RandomForestRegressor()

In [301]:
rfr.fit(x_train,y_train)

c:\Users\Jyoti Kumari\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [302]:
print("testing score:- ",rfr.score(x_test,y_test))

testing score:-  0.9674345994137763


In [303]:
print("training score:- ",rfr.score(x_train,y_train))

training score:-  0.9935531032247985


In [304]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print(gnb.score(x_test,y_test))
print(gnb.score(x_train,y_train))

0.9931818181818182
0.9954545454545455


c:\Users\Jyoti Kumari\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [305]:
from sklearn.datasets import load_iris
data=load_iris()
x=data.data
y=data.target

In [306]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [307]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [308]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print("testing score:-",gnb.score(x_test,y_test))
print("training score:",gnb.score(x_train,y_train))


testing score:- 0.9666666666666667
training score: 0.9583333333333334


In [309]:
from sklearn.ensemble import RandomForestRegressor

rf =RandomForestRegressor()

rf.fit(x_train,y_train)

print("testing score :-",rf.score(x_test,y_test))

print("training score :-",rf.score(x_train,y_train))

testing score :- 0.9487937131630648
training score :- 0.9915172206044783


In [310]:
import joblib
joblib.dump(rf,"farmer's_crop.joblib")

["farmer's_crop.joblib"]

In [311]:
model=joblib.load("farmer's_crop.joblib")

In [312]:
pred=model.predict(x_test)

In [313]:
pred

array([1.12, 2.  , 2.  , 2.  , 0.  , 0.  , 0.  , 0.  , 1.98, 1.  , 1.99,
       1.  , 1.  , 1.96, 1.  , 1.  , 0.  , 1.97, 0.  , 2.  , 1.  , 1.91,
       1.02, 1.12, 1.02, 1.  , 0.  , 0.  , 1.91, 1.  ])

In [314]:
prediction_history={"prediction_price":pred,"actual_price":y_test}

In [315]:
pd.DataFrame(prediction_history)

prediction_price  actual_price
0               1.12             1
1               2.00             2
2               2.00             2
3               2.00             2
4               0.00             0
5               0.00             0
6               0.00             0
7               0.00             0
8               1.98             2
9               1.00             1
10              1.99             2
11              1.00             1
12              1.00             1
13              1.96             2
14              1.00             1
15              1.00             1
16              0.00             0
17              1.97             2
18              0.00             0
19              2.00             2
20              1.00             1
21              1.91             2
22              1.02             1
23              1.12             1
24              1.02             1
25              1.00             1
26              0.00             0
27              0.00             0
28              1.91             1
29              1.00             1