In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\Jyoti Kumari\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print("successfully installed")

successfully installed


In [4]:
print("numpy version :-",np.__version__)

numpy version :- 2.2.5


In [ ]:
#array and list
#arry=[1,2,3,344,4,5,6]
#list=[1,2,3,"arati",True,2.5]

In [5]:
lst=[1,2,3,4,5]
print("type of list:",type(lst))
arr=np.array(lst)
print("type of array:",type(arr))

type of list: <class 'list'>
type of array: <class 'numpy.ndarray'>


In [6]:
print(arr)
print("type of array:",type(arr))

[1 2 3 4 5]
type of array: <class 'numpy.ndarray'>


In [ ]:
lst=list(range(1,20)) 

In [9]:
type(lst)
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros((5,10)) # 5 rows and 10 column
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [24]:
arr=np.ones((5,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
arr=np.linspace(1,10,5)
arr


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
arr = np.arange(1,20) # arange=to create array
type(arr)

numpy.ndarray

## 1D array convert into 2D

In [27]:
arr=np.arange(0,30)

In [ ]:
arr.reshape(5,6)  # 5 rows and 6 column

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
arr=np.random.randint(1,5,9)
arr

array([2, 3, 4, 1, 3, 1, 1, 2, 1], dtype=int32)

In [33]:
arr=np.random.randint(1,5,(5,2))
arr

array([[3, 3],
       [3, 3],
       [3, 4],
       [3, 2],
       [4, 3]], dtype=int32)

In [34]:
arr=np.random.random((5,10))
arr

array([[0.58061868, 0.54610412, 0.47284036, 0.13917099, 0.64986192,
        0.84714926, 0.47042475, 0.43734446, 0.74091582, 0.96303246],
       [0.32935118, 0.87730939, 0.98310365, 0.8033825 , 0.50799601,
        0.42081976, 0.1166402 , 0.89726029, 0.17593222, 0.57882139],
       [0.34873473, 0.35999606, 0.5363435 , 0.76467931, 0.82289202,
        0.39702319, 0.06002929, 0.71826021, 0.00772751, 0.23307254],
       [0.46660471, 0.25270865, 0.50065403, 0.48968453, 0.24024249,
        0.76444127, 0.65976595, 0.62637493, 0.26151498, 0.84020267],
       [0.68133777, 0.71225419, 0.32236698, 0.58394412, 0.32318737,
        0.1763922 , 0.12819036, 0.13319907, 0.26311593, 0.53402893]])

In [35]:
arr=np.arange(60).reshape(12,5)

In [36]:
print("arr shape:",arr.shape)

arr shape: (12, 5)


In [37]:
print("array data type:",arr.dtype)
print("dimension:",arr.ndim)
print("size",arr.size)

array data type: int64
dimension: 2
size 60


In [ ]:
arr.flatten()    # convert to 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [41]:
arr.T.shape

(5, 12)

In [43]:
#1D
arr=np.arange(30)
arr.shape
arr.size

30

In [ ]:
arr[0]   #indexing

np.int64(0)

In [ ]:
arr[0:10]  #slicing

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[0]=100


In [48]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [51]:
# 2D
arr=np.arange(60).reshape(12,5)
print(arr)
arr[1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


array([5, 6, 7, 8, 9])

In [52]:
arr=np.arange(60).reshape(12,5)
print(arr)
arr[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


np.int64(6)

In [ ]:
arr[0:5,1:2]      #row(0;5) and column(1:2)

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [54]:
arr[1:2,3:5]

array([[8, 9]])

In [55]:
arr[7:8,4][0]

np.int64(39)

In [56]:
arr[7:8,4][0]=100


In [57]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [59]:
arr[11,4]

np.int64(59)

In [60]:
arr[-1,-1]

np.int64(59)

In [61]:
arr[-1][-1]

np.int64(59)

In [62]:
arr[11][-1]

np.int64(59)

In [65]:
# 3D array:
arr=np.array(np.arange(225).reshape(5,15,3))
arr
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [66]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [68]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [70]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [ ]:
arr[:,0:1,0:1]     # puri table,row,column

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [ ]:

arr[2][3][1]=200
arr[2][3][1]

[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 200 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]
  [120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]]

 [[135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]
  [150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 169 170]
  [171 172 173]
  [174 175 176]
  [177 178 179]]

 [[180 181 182]
  [183 184 185]


np.int64(200)

In [79]:
arr=np.array([1,2,3,7,44])
arr.sort()
arr

array([ 1,  2,  3,  7, 44])

In [81]:
arr*2

array([ 2,  4,  6, 14, 88])

In [83]:
arr/2

array([ 0.5,  1. ,  1.5,  3.5, 22. ])

In [82]:
arr-1

array([ 0,  1,  2,  6, 43])

In [80]:
arr+2

array([ 3,  4,  5,  9, 46])

In [84]:
arr1=[2,3,45,6,7]
arr+arr1

array([ 3,  5, 48, 13, 51])