In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\Jyoti Kumari\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print("successfully installed")

successfully installed


In [3]:
print("numpy version :-",np.__version__)

numpy version :- 2.2.5


In [4]:
#array and list
#arry=[1,2,3,344,4,5,6]
#list=[1,2,3,"arati",True,2.5]

In [5]:
lst=[1,2,3,4,5]
print("type of list:",type(lst))
arr=np.array(lst)
print("type of array:",type(arr))

type of list: <class 'list'>
type of array: <class 'numpy.ndarray'>


In [6]:
print(arr)
print("type of array:",type(arr))

[1 2 3 4 5]
type of array: <class 'numpy.ndarray'>


In [7]:
lst=list(range(1,20)) 

In [8]:
type(lst)
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [10]:
arr=np.zeros((5,10)) # 5 rows and 10 column
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [12]:
arr=np.ones((5,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
arr=np.linspace(1,10,5)
arr


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
arr = np.arange(1,20) # arange=to create array
type(arr)

numpy.ndarray

## 1D array convert into 2D

In [15]:
arr=np.arange(0,30)

In [16]:
arr.reshape(5,6)  # 5 rows and 6 column

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [18]:
arr=np.random.randint(1,5,9)
arr

array([4, 2, 4, 4, 3, 4, 3, 2, 2], dtype=int32)

In [19]:
arr=np.random.randint(1,5,(5,2))
arr

array([[3, 1],
       [4, 4],
       [2, 4],
       [1, 4],
       [3, 4]], dtype=int32)

In [20]:
arr=np.random.random((5,10))
arr

array([[0.62999975, 0.61758428, 0.25025587, 0.76294351, 0.34715189,
        0.72868798, 0.30751521, 0.07185885, 0.36168768, 0.6278927 ],
       [0.31921352, 0.00622392, 0.02025883, 0.4847028 , 0.74657634,
        0.14959128, 0.36290987, 0.50962506, 0.65300646, 0.41637202],
       [0.70406251, 0.54563253, 0.61648632, 0.54969621, 0.33964317,
        0.21698405, 0.84671267, 0.55577627, 0.73506099, 0.85522099],
       [0.99968826, 0.53807314, 0.98519238, 0.94715411, 0.06956061,
        0.71288071, 0.79885848, 0.24644159, 0.12376698, 0.20846211],
       [0.57464299, 0.4965419 , 0.90103728, 0.72936095, 0.58410639,
        0.56871415, 0.40971598, 0.47772865, 0.54439099, 0.55963938]])

In [21]:
arr=np.arange(60).reshape(12,5)

In [22]:
print("arr shape:",arr.shape)

arr shape: (12, 5)


In [23]:
print("array data type:",arr.dtype)
print("dimension:",arr.ndim)
print("size",arr.size)

array data type: int64
dimension: 2
size 60


In [24]:
arr.flatten()    # convert to 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [25]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [27]:
arr.T.shape

(5, 12)

In [28]:
#1D
arr=np.arange(30)
arr.shape
arr.size

30

In [29]:
arr[0]   #indexing

np.int64(0)

In [30]:
arr[0:10]  #slicing

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[0]=100


In [32]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [33]:
# 2D
arr=np.arange(60).reshape(12,5)
print(arr)
arr[1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


array([5, 6, 7, 8, 9])

In [34]:
arr=np.arange(60).reshape(12,5)
print(arr)
arr[1,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


np.int64(6)

In [35]:
arr[0:5,1:2]      #row(0;5) and column(1:2)

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [36]:
arr[1:2,3:5]

array([[8, 9]])

In [37]:
arr[7:8,4][0]

np.int64(39)

In [38]:
arr[7:8,4][0]=100


In [39]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [40]:
arr[11,4]

np.int64(59)

In [41]:
arr[-1,-1]

np.int64(59)

In [42]:
arr[-1][-1]

np.int64(59)

In [43]:
arr[11][-1]

np.int64(59)

In [44]:
# 3D array:
arr=np.array(np.arange(225).reshape(5,15,3))
arr
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [45]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [46]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [47]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [48]:
arr[:,0:1,0:1]     # puri table,row,column

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [49]:

arr[2][3][1]=200
arr[2][3][1]

np.int64(200)

In [50]:
arr=np.array([1,2,3,7,44])
arr.sort()
arr

array([ 1,  2,  3,  7, 44])

In [51]:
arr*2

array([ 2,  4,  6, 14, 88])

In [52]:
arr/2

array([ 0.5,  1. ,  1.5,  3.5, 22. ])

In [53]:
arr-1

array([ 0,  1,  2,  6, 43])

In [54]:
arr+2

array([ 3,  4,  5,  9, 46])

In [55]:
arr1=[2,3,45,6,7]
arr+arr1

array([ 3,  5, 48, 13, 51])